---
name: Data-CloudWeights
version: 0.1.9
author:
  - 'Peter Flanigan, C<< <Support at RoxSoft.co.uk> >>'
abstract: Calculate values for an HTML tag cloud
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::Accessor::Fast: 0.31
  perl: 5.8
provides:
  Data::CloudWeights:
    file: lib/Data/CloudWeights.pm
    version: 0.1.9
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
